name: 'dbt_training_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_training_project'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  dbt_training_project:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: datamart_analytics # optional. By default it's taken from profile.yml
